export const USER_REGISTER = "USER_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const VALIDATE_RESERVATION = "VALIDATE_RESERVATION";
export const ADD_RESERVATION = "ADD_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const RESERVATIONS_LOADING = "RESERVATIONS_LOADING";

export const GET_GAMES = "GET_GAMES";
export const GAMES_LOADING = "GAMES_LOADING";


